language: python
python:
  - "3.8"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - python test.py

deploy:
  provider: heroku
  api_key: "${HEROKU_API_KEY}"
  app: jokeandpickupapi
  on: master
